    version: "3.1"

    services:
        php:
            container_name: docker-php-laravel
            build:
                context: .
                dockerfile: Dockerfile
            ports:
            - "3001:80"
            volumes:
                - ".:/var/www/html"



